# FUNCIONES MAS COMUNES EN PANDAS

In [1]:
import pandas as pd
df_books = pd.read_csv('https://github.com/cesarmayta/datasets/raw/refs/heads/main/libros.csv')
df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

# INFO()

In [2]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    object
 1   Author       550 non-null    object
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB

# MEMORY_USAGE()

In [3]:
df_books.memory_usage(deep=True)

Index            132
Name           56763
Author         34756
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          32040
dtype: int64

# DESCRIBE()

In [4]:
df_books.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

# HEAD Y TAIL

In [5]:
df_books.head(5)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [6]:
df_books.tail(5)

,Name,Author,User Rating,Reviews,Price,Year,Genre
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

# VALUE_COUNTS()

In [7]:
df_books['Genre'].value_counts()

Genre
Non Fiction    310
Fiction        240
Name: count, dtype: int64

# FUNCIONES PARA PROCESAMIENTO DE DATOS

## LIMPIEZA DE VALORES NULOS

In [8]:
df_books.isnull().value_counts()

Name   Author  User Rating  Reviews  Price  Year   Genre
False  False   False        False    False  False  False    550
Name: count, dtype: int64

In [9]:
import numpy as np
df_books['Price'] = np.nan
df_books.isnull().value_counts()

Name   Author  User Rating  Reviews  Price  Year   Genre
False  False   False        False    True   False  False    550
Name: count, dtype: int64

In [12]:
df_books.isnull().sum()

Name             0
Author           0
User Rating      0
Reviews          0
Price          200
Year             0
Genre            0
dtype: int64

In [11]:
df_books.loc[df_books['Year']<2016,'Price'] = 1000

In [13]:
df_books.dropna()

,Name,Author,User Rating,Reviews,Price,Year,Genre
1,11/22/63: A Novel,Stephen King,4.6,2052,1000.0,2011,Fiction
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,1000.0,2011,Fiction
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735,1000.0,2014,Fiction
11,A Patriot's History of the United States: From...,Larry Schweikart,4.6,460,1000.0,2010,Non Fiction
12,A Stolen Life: A Memoir,Jaycee Dugard,4.6,4149,1000.0,2011,Non Fiction
...,...,...,...,...,...,...,...
538,Winter of the World: Book Two of the Century T...,Ken Follett,4.5,10760,1000.0,2012,Fiction
539,Women Food and God: An Unexpected Path to Almo...,Geneen Roth,4.2,1302,1000.0,2010,Non Fiction
540,Wonder,R. J. Palacio,4.8,21625,1000.0,2013,Fiction
541,Wonder,R. J. Palacio,4.8,21625,1000.0,2014,Fiction
542,Wonder,R. J. Palacio,4.8,21625,1000.0,2015,Fiction

In [14]:
df_books.fillna(0)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,0.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,1000.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,0.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,0.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,0.0,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,0.0,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,0.0,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,0.0,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,0.0,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,0.0,2019,Non Fiction

# LIMPIEZA DE VALORES DUPLICADOS

In [15]:
df_books = pd.concat([df_books,df_books.tail(3)],ignore_index=True)
df_books.tail(10)

,Name,Author,User Rating,Reviews,Price,Year,Genre
543,Wonder,R. J. Palacio,4.8,21625,NaN,2016,Fiction
544,Wonder,R. J. Palacio,4.8,21625,NaN,2017,Fiction
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,NaN,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2019,Non Fiction
550,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2017,Non Fiction
551,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2018,Non Fiction
552,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2019,Non Fiction

In [16]:
df_books.drop_duplicates(keep='last',inplace=True)
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,NaN,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,1000.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,NaN,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,NaN,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,NaN,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,NaN,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2016,Non Fiction
550,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2017,Non Fiction
551,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2018,Non Fiction
552,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2019,Non Fiction

# SORT()

In [17]:
df_books.sort_values('Year')

,Name,Author,User Rating,Reviews,Price,Year,Genre
25,Arguing with Idiots: How to Stop Small Minds a...,Glenn Beck,4.6,798,1000.0,2009,Non Fiction
520,Under the Dome: A Novel,Stephen King,4.3,6740,1000.0,2009,Fiction
498,Three Cups of Tea: One Man's Mission to Promot...,Greg Mortenson,4.3,3319,1000.0,2009,Non Fiction
524,Watchmen,Alan Moore,4.8,3829,1000.0,2009,Fiction
512,True Compass: A Memoir,Edward M. Kennedy,4.5,438,1000.0,2009,Non Fiction
...,...,...,...,...,...,...,...
462,The Silent Patient,Alex Michaelides,4.5,27536,NaN,2019,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,NaN,2019,Non Fiction
41,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,4.9,14344,NaN,2019,Fiction
552,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2019,Non Fiction
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,NaN,2019,Fiction

In [18]:
df_books.sort_values('Year',ascending=False)

,Name,Author,User Rating,Reviews,Price,Year,Genre
552,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,NaN,2019,Non Fiction
529,What Should Danny Do? (The Power to Choose Ser...,Adir Levy,4.8,8170,NaN,2019,Fiction
522,Unicorn Coloring Book: For Kids Ages 4-8 (US E...,Silly Bear,4.8,6108,NaN,2019,Non Fiction
521,Unfreedom of the Press,Mark R. Levin,4.9,5956,NaN,2019,Non Fiction
380,The Four Agreements: A Practical Guide to Pers...,Don Miguel Ruiz,4.7,23308,NaN,2019,Non Fiction
...,...,...,...,...,...,...,...
134,Going Rogue: An American Life,Sarah Palin,4.6,1636,1000.0,2009,Non Fiction
139,Good to Great: Why Some Companies Make the Lea...,Jim Collins,4.5,3457,1000.0,2009,Non Fiction
14,"Act Like a Lady, Think Like a Man: What Men Re...",Steve Harvey,4.6,5013,1000.0,2009,Non Fiction
512,True Compass: A Memoir,Edward M. Kennedy,4.5,438,1000.0,2009,Non Fiction
513,"Twilight (The Twilight Saga, Book 1)",Stephenie Meyer,4.7,11676,1000.0,2009,Fiction